In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_openml

In [7]:
b_cancer= fetch_openml(name="Breast-cancer", version=1, as_frame=True)
df=b_cancer.frame
df.head()

,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat,Class
0,40-49,premeno,15-19,0-2,yes,3,right,left_up,no,recurrence-events
1,50-59,ge40,15-19,0-2,no,1,right,central,no,no-recurrence-events
2,50-59,ge40,35-39,0-2,no,2,left,left_low,no,recurrence-events
3,40-49,premeno,35-39,0-2,yes,3,right,left_low,yes,no-recurrence-events
4,40-49,premeno,30-34,3-5,yes,2,left,right_up,no,recurrence-events

In [13]:
print(df.isnull().sum())

age            0
menopause      0
tumor-size     0
inv-nodes      0
node-caps      8
deg-malig      0
breast         0
breast-quad    1
irradiat       0
Class          0
dtype: int64

In [14]:
df.describe()

,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat,Class
count,286,286,286,286,278,286,286,285,286,286
unique,6,3,11,7,2,3,2,5,2,2
top,50-59,premeno,30-34,0-2,no,2,left,left_low,no,no-recurrence-events
freq,96,150,60,213,222,130,152,110,218,201

In [16]:
df.fillna({'node-caps':"yes", 'breast-quad':'left_up'}, inplace=True)

In [30]:
X=df[["breast", "menopause"]]
y=df["deg-malig"]

In [41]:
le=LabelEncoder()

df["breast"]=le.fit_transform(df["breast"])
df["menopause"]=le.fit_transform(df["menopause"])

X_train, X_test, y_train, y_test=train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [42]:
scaler=StandardScaler()
# le=LabelEncoder()
# ohc=OneHotEncoder()
# df["breast"]=ohc.fit_transform(df["breast"])
# df["menopause"]=ohc.fit_transform(df["menopause"])

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

ValueError: could not convert string to float: 'right'

In [ ]:
model=SVC(kernel="linear")
model.fit(X_train, y_train)

y_pred=model.predict()