In [16]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [4]:
df = sns.load_dataset('titanic')

In [5]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [9]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [13]:
df.fillna({'age':df['age'].mean()},inplace=True)

In [14]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [15]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [17]:
le = LabelEncoder()
df['sex']=le.fit_transform(df['sex'])

In [18]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,0,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,0,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,0,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,1,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,0,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,0,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,1,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,1,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [24]:
df = df.drop(['sibsp','pclass','parch','who','embark_town'],axis=1)

In [25]:
df

,survived,sex,age,fare,embarked,class,adult_male,deck,alive,alone
0,0,1,22.000000,7.2500,S,Third,True,NaN,no,False
1,1,0,38.000000,71.2833,C,First,False,C,yes,False
2,1,0,26.000000,7.9250,S,Third,False,NaN,yes,True
3,1,0,35.000000,53.1000,S,First,False,C,yes,False
4,0,1,35.000000,8.0500,S,Third,True,NaN,no,True
...,...,...,...,...,...,...,...,...,...,...
886,0,1,27.000000,13.0000,S,Second,True,NaN,no,True
887,1,0,19.000000,30.0000,S,First,False,B,yes,True
888,0,0,29.699118,23.4500,S,Third,False,NaN,no,False
889,1,1,26.000000,30.0000,C,First,True,C,yes,True
890,0,1,32.000000,7.7500,Q,Third,True,NaN,no,True