#### https://www.datacamp.com/tutorial/decision-tree-classification-python

#### https://www.youtube.com/watch?v=ynTCUngbFHA

Decision tree can be used for both classificaton oroblem and regression problems, however
here we will cover it with regard to classification problem only.

let us say we have (age = some no.) [ look at the image bellow ] we can use if else and elif to create conditions, now every condition will either get satisfied it or no. If yes then do something(i.e we execute some code lines) and if not then we do something else , now when these things when represented in a diagramatically form then it takes the shape of a tree with their nodes as the conditions

![alt text](ref1.png)

here is the screenshot of the dataset names tennis dataset

![alt text](ref2.png)

one thing that can be noticed here is that all of the coloumns are independent features, 
based on this we will try to predict whether a person NAMED : 'PRANAV' will play tennis or not

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, r2_score, accuracy_score, classification_report
from sklearn.tree import DecisionTreeClassifier

In [3]:
df = pd.read_csv("PlayTennis.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Day         14 non-null     object
 1   Outlook     14 non-null     object
 2   Temp        14 non-null     object
 3   Humidity    14 non-null     object
 4   Wind        14 non-null     object
 5   PlayTennis  14 non-null     object
dtypes: object(6)
memory usage: 804.0+ bytes

In [5]:
df.head()

  Day   Outlook  Temp Humidity    Wind PlayTennis
0  D1     Sunny   Hot     High    Weak         No
1  D2     Sunny   Hot     High  Strong         No
2  D3  Overcast   Hot     High    Weak        Yes
3  D4      Rain  Mild     High    Weak        Yes
4  D5      Rain  Cool   Normal    Weak        Yes

In [12]:
X = df[["Outlook", "Temp", "Humidity", "Wind"]]
y = df["PlayTennis"]

# since outlook, temp, humidity and wind all are in string therefore we will have to convert into
# numerical data therefor we use label encoder

le=LabelEncoder()

df['Outlook']=le.fit_transform(df['Outlook'])
df['Temp']=le.fit_transform(df['Temp'])
df['Humidity']=le.fit_transform(df['Humidity'])
df['Wind']=le.fit_transform(df['Wind'])

# print(df['Outlook'])
print(X)

    Outlook  Temp  Humidity  Wind
0         2     1         0     1
1         2     1         0     0
2         0     1         0     1
3         1     2         0     1
4         1     0         1     1
5         1     0         1     0
6         0     0         1     0
7         2     2         0     1
8         2     0         1     1
9         1     2         1     1
10        2     2         1     0
11        0     2         0     0
12        0     1         1     1
13        1     2         0     0

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [14]:
model = DecisionTreeClassifier(criterion="gini", random_state=42)
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [15]:
model.score(X_test, y_test)

1.0

In [17]:
X_test[:3]

    Outlook  Temp  Humidity  Wind
9         1     2         1     1
11        0     2         0     0
0         2     1         0     1

In [18]:
y_test[:3]

9     Yes
11    Yes
0      No
Name: PlayTennis, dtype: object

In [19]:
model.predict(X_test[:3])

array(['Yes', 'Yes', 'No'], dtype=object)